In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime
#Colorama
from colorama import Fore, Back, Style # For text colors
y_= Fore.CYAN
m_= Fore.WHITE

# Bitcoin histerical data

In [ ]:
# The Ticker module, which allows you to access ticker data in a more Pythonic way:
# history = get historical market data
# period= max will get us data from start of the bit coin to today (2022-09-23) 
# interval = 1d will allow us to get data on daily basis
btc = yf.Ticker("BTC-USD").history(period = "max", interval="1d") 
btc.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2929 entries, 2014-09-17 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          2929 non-null   float64
 1   High          2929 non-null   float64
 2   Low           2929 non-null   float64
 3   Close         2929 non-null   float64
 4   Volume        2929 non-null   int64
 5   Dividends     2929 non-null   int64
 6   Stock Splits  2929 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 183.1 KB

In [ ]:
btc.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,0,0
2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,0,0
2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,0,0
2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,0,0
2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,0,0

In [ ]:
print(f"{m_}Total records:{y_}{btc.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{btc.dtypes}")

Total records:(2929, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Etherium histerical data

In [ ]:
eth = yf.Ticker("ETH-USD").history(period = "max", interval="1d")
eth.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
eth.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2017-11-09,308.644989,329.451996,307.056000,320.884003,893249984,0,0
2017-11-10,320.670990,324.717987,294.541992,299.252991,885985984,0,0
2017-11-11,298.585999,319.453003,298.191986,314.681000,842300992,0,0
2017-11-12,314.690002,319.153015,298.513000,307.907990,1613479936,0,0
2017-11-13,307.024994,328.415009,307.024994,316.716003,1041889984,0,0

In [ ]:
print(f"{m_}Total records:{y_}{eth.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{eth.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Litcoin histerical data

In [ ]:
ltc = yf.Ticker("LTC-USD").history(period = "max", interval="1d")
ltc.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2929 entries, 2014-09-17 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          2929 non-null   float64
 1   High          2929 non-null   float64
 2   Low           2929 non-null   float64
 3   Close         2929 non-null   float64
 4   Volume        2929 non-null   int64
 5   Dividends     2929 non-null   int64
 6   Stock Splits  2929 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 183.1 KB

In [ ]:
ltc.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17,5.08589,5.17077,4.96595,5.05855,3071840,0,0
2014-09-18,5.06543,5.06543,4.57996,4.68523,4569260,0,0
2014-09-19,4.68729,4.75582,4.25435,4.32777,3917450,0,0
2014-09-20,4.32920,4.61608,4.20219,4.28644,5490660,0,0
2014-09-21,4.26307,4.30013,4.15499,4.24592,2931220,0,0

In [ ]:
print(f"{m_}Total records:{y_}{ltc.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{ltc.dtypes}")

Total records:(2929, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Ripple Histerical data

In [ ]:
xrp = yf.Ticker("XRP-USD").history(period = "max", interval="1d")
xrp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
print(f"{m_}Total records:{y_}{xrp.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{xrp.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Tether Histerical Data

In [ ]:
tether = yf.Ticker("USDT-USD").history(period = "max", interval="1d")
tether.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
tether.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-09-19,1.000008,1.000175,0.999945,1.000106,56769197831,0,0
2022-09-20,1.000104,1.000194,1.000037,1.000060,50515394641,0,0
2022-09-21,1.000055,1.000194,1.000033,1.000086,63560607050,0,0
2022-09-22,1.000106,1.000172,0.999971,0.999984,54330130153,0,0
2022-09-23,0.999984,1.000032,0.999958,0.999995,54475481088,0,0

In [ ]:
print(f"{m_}Total records:{y_}{tether.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{tether.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# USD Coin Histerical Data

In [ ]:
USD_Coin = yf.Ticker("USDC-USD").history(period = "max", interval="1d")
USD_Coin.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1447 entries, 2018-10-08 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1447 non-null   float64
 1   High          1447 non-null   float64
 2   Low           1447 non-null   float64
 3   Close         1447 non-null   float64
 4   Volume        1447 non-null   int64
 5   Dividends     1447 non-null   int64
 6   Stock Splits  1447 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 90.4 KB

In [ ]:
print(f"{m_}Total records:{y_}{USD_Coin.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{USD_Coin.dtypes}")

Total records:(1447, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# BNB Coin Histerical Data

In [ ]:
BNB_Coin = yf.Ticker("BNB-USD").history(period = "max", interval="1d")
BNB_Coin.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
print(f"{m_}Total records:{y_}{BNB_Coin.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{BNB_Coin.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Cardano Histerical Data

In [ ]:
ADA_Coin = yf.Ticker("ADA-USD").history(period = "max", interval="1d")
ADA_Coin.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
print(f"{m_}Total records:{y_}{ADA_Coin.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{ADA_Coin.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# DOGE coin Histerical Data

In [ ]:
DOGE_Coin = yf.Ticker("DOGE-USD").history(period = "max", interval="1d")
DOGE_Coin.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1780 entries, 2017-11-09 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1780 non-null   float64
 1   High          1780 non-null   float64
 2   Low           1780 non-null   float64
 3   Close         1780 non-null   float64
 4   Volume        1780 non-null   int64
 5   Dividends     1780 non-null   int64
 6   Stock Splits  1780 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 111.2 KB

In [ ]:
print(f"{m_}Total records:{y_}{DOGE_Coin.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{DOGE_Coin.dtypes}")

Total records:(1780, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Polkadot coin  Histerical Data

In [ ]:
DOT_Coin = yf.Ticker("DOT-USD").history(period = "max", interval="1d")
DOT_Coin.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 765 entries, 2020-08-20 to 2022-09-23
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          765 non-null    float64
 1   High          765 non-null    float64
 2   Low           765 non-null    float64
 3   Close         765 non-null    float64
 4   Volume        765 non-null    int64
 5   Dividends     765 non-null    int64
 6   Stock Splits  765 non-null    int64
dtypes: float64(4), int64(3)
memory usage: 47.8 KB

In [ ]:
print(f"{m_}Total records:{y_}{DOT_Coin.shape}\n")
print(f"{m_}Data types of data columns: \n{y_}{DOT_Coin.dtypes}")

Total records:(765, 7)

Data types of data columns:
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends         int64
Stock Splits      int64
dtype: object

# Exporting Data of All 10 Types of Cryptocurrencies Into Separate CSV Files

In [ ]:
Path = 'F:\\Ml files\\crypto price prediction\\data\\'

In [ ]:
# to_csv function can take a datafram and file name as input and exports the data into the data folder 
def to_csv(dataframe, file_name):
    return dataframe.to_csv(Path+file_name, index = True)

In [ ]:
to_csv(btc, 'bitcoin_data.csv')
to_csv(eth, 'etherium_data.csv')
to_csv(ltc, 'litcoin_data.csv')
# to_csv(xrp, 'ripple_data.csv')
# to_csv(tether, 'tether_data.csv')
# to_csv(USD_Coin, 'USD_Coin_data.csv')
to_csv(BNB_Coin, 'BNB_Coin_data.csv')
# to_csv(ADA_Coin, 'Cardano_data.csv')
# to_csv(DOGE_Coin, 'doge_data.csv')
# to_csv(DOT_Coin, 'polkadot_data.csv')